version: '3.8'

services:
  dotnet-service:
    build:
      context: ./dotnet-app
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./dotnet-app:/src
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1

  go-service:
    build:
      context: ./go-app
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./go-app:/app

  python-service:
    build:
      context: ./python-app
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./python-app:/app

  node-service:
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/app
      - /app/node_modules # Avoid overwriting container node_modules with host path
